---
development:
  dialect: postgres
  database: {{envOr "DATABASE_NAME" "development"}}
  user: {{envOr "DATABASE_USER" "postgres"}}
  password: {{envOr "DATABASE_PASSWORD" "postgres"}}
  host: {{envOr "DATABASE_HOST" "postgres"}}
  port: {{envOr "DATABASE_PORT" "5432"}}
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@postgres:5432/portal_test?sslmode=disable"}}

# production:
#   url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@postgres:5432/portal_production?sslmode=disable"}}
